name: congress_explorer
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  congress_repository:
    path: packages/congress_repository
  download: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  icon_craft: ^0.1.0+3
  intl: ^0.19.0
  logger: ^2.3.0
  path_provider: ^2.1.3
  recase: ^4.1.0
  skeletonizer: ^1.3.0
  timeago: ^3.6.1
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets: 
    - assets/
